using System;
using System.Collections.Generic;
using System.Text;
using System.Windows.Input;
using System.Windows.Media;
using System.Xml.Serialization;
using Common.Drawing.InspectionInformation;

namespace Common.Drawing
{
    public class PropertiesGraphicsStripAlign : PropertiesGraphicsBase
    {
        private double cpX;
        private double cpY;
        private int nID;

        #region Ctor.
        // For XmlSerializer
        public PropertiesGraphicsStripAlign()
        {
            // XML로의 저장을 위해 기본 생성자가 필요하다.
            System.Diagnostics.Debug.WriteLine("PropertiesGraphicsGuideLine 기본 생성자 호출, 아무일도 하지 않는다.");
        }

        public PropertiesGraphicsStripAlign(GraphicsStripAlign stripalign)
        {
            if (stripalign == null)
            {
                throw new ArgumentNullException("guideLine");
            }

            this.cpX = stripalign.cpX;
            this.cpY = stripalign.cpY;
            this.nID = stripalign.nID;
            this.lineWidth = stripalign.LineWidth;
            this.regionType = stripalign.RegionType;
            this.objectColor = stripalign.ObjectColor;
            this.actualScale = stripalign.ActualScale;
            this.Id = stripalign.ID;
            this.selected = stripalign.IsSelected;
            this.caption = stripalign.Caption;
        }
        #endregion

        public override GraphicsBase CreateGraphics()
        {
            lineWidth = 2; // Default thickness.

            actualScale = (actualScale > 0) ? actualScale : 1.0;
            GraphicsStripAlign b = new GraphicsStripAlign(cpX, cpY, nID, lineWidth, objectColor, actualScale);

            // GraphicsBase contains new ID generated by constructor.
            // This is OK if this instance is loaded from XML file.
            // But if this instance is part of commands history,
            // it contains ID which should be set in GraphicsBase.
            // This rule is applied to all SerializedGraphicsBase-derived
            // classes.
            if (this.Id != 0)       // from command history, not from file
            {
                b.ID = this.Id;
                b.IsSelected = this.selected;
            }

            return b;
        }

        #region Properties
        public int ID
        {
            get
            {
                return Id;
            }
            set
            {
                Id = value;
            }
        }

        public double CPX
        {
            get
            {
                return cpX;
            }
            set
            {
                cpX = value;
            }
        }

        public double CPY
        {
            get
            {
                return cpY;
            }
            set
            {
                cpY = value;
            }
        }

        public int IDX
        {
            get
            {
                return nID;
            }
            set
            {
                nID = value;
            }
        }

        public GraphicsRegionType RegionType
        {
            get
            {
                return regionType;
            }
            set
            {
                regionType = value;
            }

        }

        public Color ObjectColor
        {
            get
            {
                return objectColor;
            }
            set
            {
                objectColor = value;
            }
        }

        public string Caption
        {
            get
            {
                return caption;
            }
            set
            {
                caption = value;
            }
        }
        #endregion Properties
    }
}
