using System;
using System.Collections.Generic;
using System.Text;
using System.Windows.Input;
using System.Windows.Media;
using System.Xml.Serialization;
using Common.Drawing.MarkingInformation;

namespace Common.Drawing
{
    public class PropertiesGraphicsTBDMark : PropertiesGraphicsBase
    {
        private double left;
        private double top;
        private double right;
        private double bottom;

        private bool isCanMove;
        private bool isValidRegion;
        private double rotate;
        private string motherID;
        private GraphicsRegionType regiontype;

        #region Ctor.
        // For XmlSerializer
        public PropertiesGraphicsTBDMark()
        {
            // XML로의 저장을 위해 기본 생성자가 필요하다.
        }

        public PropertiesGraphicsTBDMark(GraphicsTBD rectangle)
        {
            if (rectangle == null)
            {
                throw new ArgumentNullException("idmark");
            }

            this.left = rectangle.Left;
            this.top = rectangle.Top;
            this.right = rectangle.Right;
            this.bottom = rectangle.Bottom;
            this.lineWidth = rectangle.LineWidth;
            this.regionType = rectangle.RegionType;
            this.objectColor = rectangle.ObjectColor;
            this.actualScale = rectangle.ActualScale;
            this.Id = rectangle.ID;
            this.motherID = rectangle.MarkID;
            this.selected = rectangle.IsSelected;
            this.isValidRegion = rectangle.IsValidRegion;
            this.rotate = rectangle.Rotate;
            this.caption = rectangle.Caption;
            this.markInfo = rectangle.MarkInfo;
            this.inspectionItems = null;
            this.regiontype = rectangle.RegionType;
        }
        #endregion

        public override GraphicsBase CreateGraphics()
        {
            lineWidth = 2; // Default thickness.

            MarkItem markinfo = new MarkItem();
            markinfo = MarkingItemHelper.CopyMarkItem(this.markInfo);

            actualScale = (actualScale > 0) ? actualScale : 1.0;
            GraphicsTBD b = new GraphicsTBD(left, top, right, bottom, lineWidth, objectColor,
                                                   actualScale, 0, caption, "", markinfo, regiontype);
            b.IsValidRegion = isValidRegion;
            b.MarkID = motherID;

            // GraphicsBase contains new ID generated by constructor.
            // This is OK if this instance is loaded from XML file.
            // But if this instance is part of commands history,
            // it contains ID which should be set in GraphicsBase.
            // This rule is applied to all SerializedGraphicsBase-derived
            // classes.
            if (this.Id != 0)       // from command history, not from file
            {
                b.ID = this.Id;
                b.IsSelected = this.selected;
            }

            return b;
        }

        #region Properties
        public int ID
        {
            get { return Id; }
            set { Id = value; }
        }

        public string MotherROIID
        {
            get { return motherID; }
            set { motherID = value; }
        }

        public double Left
        {
            get { return left; }
            set { left = value; }
        }

        public double Top
        {
            get { return top; }
            set { top = value; }
        }

        public double Right
        {
            get { return right; }
            set { right = value; }
        }

        public double Bottom
        {
            get { return bottom; }
            set { bottom = value; }
        }

        public double Rotate
        {
            get { return rotate; }
            set { rotate = value; }
        }

        public GraphicsRegionType RegionType
        {
            get { return regionType; }
            set { regionType = value; }
        }


        public bool IsCanMove
        {
            get { return isCanMove; }
            set { isCanMove = value; }
        }

        public bool IsValidRegion
        {
            get { return isValidRegion; }
            set { isValidRegion = value; }
        }

        public Color ObjectColor
        {
            get { return objectColor; }
            set { objectColor = value; }
        }

        public string Caption
        {
            get { return caption; }
            set { caption = value; }
        }

        public MarkItem MarkInfo
        {
            get { return markInfo; }
            set { markInfo = value; }
        }
        #endregion Properties
    }
}





