// http://www.codeproject.com/KB/WPF/WPF_DrawTools.aspx
// Author : Alex Fr
// This article, along with any associated source code and files, is licensed under The Code Project Open License (CPOL)

using System;
using System.Collections.Generic;
using System.Text;
using System.Windows.Input;
using System.Windows.Media;
using System.Xml.Serialization;
using Common.Drawing.InspectionInformation;

// Commented by suoow2.

namespace Common.Drawing
{
    /// <summary>
    /// Rectangle object properties.
    /// </summary>
    public class PropertiesGraphicsRectangle : PropertiesGraphicsBase
    {
        private double left;
        private double top;
        private double right;
        private double bottom;

        private IterationSymmetryInformation symmetryValue;
        private IterationInformation iterationValue;
        private IterationInformation blockIterationValue;
        private bool isFiducialRegion;
        private bool isCanMove;
        private bool isValidRegion;
        private GraphicsBase motherROI;
        private int motherROIID = -1;
        private int iterationXPosition;
        private int iterationYPosition;

        #region Ctor.
        // For XmlSerializer
        public PropertiesGraphicsRectangle()
        {
            // XML로의 저장을 위해 기본 생성자가 필요하다.
        }

        public PropertiesGraphicsRectangle(GraphicsRectangle rectangle)
        {
            if (rectangle == null)
            {
                throw new ArgumentNullException("rectangle");
            }

            this.left = rectangle.Left;
            this.top = rectangle.Top;
            this.right = rectangle.Right;
            this.bottom = rectangle.Bottom;
            this.lineWidth = rectangle.LineWidth;
            this.regionType = rectangle.RegionType;
            this.objectColor = rectangle.ObjectColor;
            this.actualScale = rectangle.ActualScale;
            this.Id = rectangle.ID;
            this.selected = rectangle.IsSelected;
            this.symmetryValue = rectangle.SymmetryValue;
            this.iterationValue = rectangle.IterationValue;
            this.iterationXPosition = rectangle.IterationXPosition;
            this.iterationYPosition = rectangle.IterationYPosition;
            this.blockIterationValue = rectangle.BlockIterationValue;
            this.isFiducialRegion = rectangle.IsFiducialRegion;
            this.isValidRegion = rectangle.IsValidRegion;
            this.motherROI = rectangle.MotherROI;
            this.caption = rectangle.Caption;

            if (rectangle.MotherROI != null)
            {
                this.motherROIID = rectangle.MotherROI.ID; // 복원시 Mother ROI로의 추적성을 확보하기 위해 필요하다.
            }

            if (rectangle.InspectionList != null)
            {
                inspectionItems = new InspectionItem[rectangle.InspectionList.Count];
                int nIndex = 0;
                foreach (InspectionItem inspectionElement in rectangle.InspectionList)
                {
                    inspectionItems[nIndex++] = inspectionElement;
                }
            }
        }
        #endregion

        public override GraphicsBase CreateGraphics()
        {
            lineWidth = 2; // Default thickness.

            List<InspectionItem> inspectionList = new List<InspectionItem>();
            foreach (InspectionItem inspectionElement in inspectionItems)
            {
                inspectionList.Add(InspectionItemHelper.CopyInspectionItem(inspectionElement));
            }

            actualScale = (actualScale > 0) ? actualScale : 1.0;
            GraphicsRectangle b = new GraphicsRectangle(left, top, right, bottom, lineWidth, regionType, objectColor,
                                                   actualScale, symmetryValue, iterationValue, blockIterationValue,
                                                   isFiducialRegion, motherROI,
                                                   caption, inspectionList,
                                                   iterationXPosition, iterationYPosition);
            b.IsValidRegion = isValidRegion;
            b.MotherROIID = motherROIID;

            // GraphicsBase contains new ID generated by constructor.
            // This is OK if this instance is loaded from XML file.
            // But if this instance is part of commands history,
            // it contains ID which should be set in GraphicsBase.
            // This rule is applied to all SerializedGraphicsBase-derived
            // classes.
            if (this.Id != 0)       // from command history, not from file
            {
                b.ID = this.Id;
                b.IsSelected = this.selected;
            }

            return b;
        }

        #region Properties
        public int ID
        {
            get { return Id; }
            set { Id = value; }
        }

        public int MotherROIID
        {
            get { return motherROIID; }
            set { motherROIID = value; }
        }

        public double Left
        {
            get { return left; }
            set { left = value; }
        }

        public double Top
        {
            get { return top; }
            set { top = value; }
        }

        public double Right
        {
            get { return right; }
            set { right = value; }
        }

        public double Bottom
        {
            get { return bottom; }
            set { bottom = value; }
        }

        public GraphicsRegionType RegionType
        {
            get { return regionType; }
            set { regionType = value; }
        }

        public IterationSymmetryInformation SymmetryValue
        {
            get { return symmetryValue; }
            set { symmetryValue = value; }
        }

        public IterationInformation IterationValue
        {
            get { return iterationValue; }
            set { iterationValue = value; }
        }

        public int IterationXPosition
        {
            get { return iterationXPosition; }
            set { iterationXPosition = value; }
        }

        public int IterationYPosition
        {
            get { return iterationYPosition; }
            set { iterationYPosition = value; }
        }

        public IterationInformation BlockIterationValue
        {
            get { return blockIterationValue; }
            set { blockIterationValue = value; }
        }

        public bool IsFiducialRegion
        {
            get { return isFiducialRegion; }
            set { isFiducialRegion = value; }
        }

        public bool IsCanMove
        {
            get { return isCanMove; }
            set { isCanMove = value; }
        }

        public bool IsValidRegion
        {
            get { return isValidRegion; }
            set { isValidRegion = value; }
        }

        public Color ObjectColor
        {
            get { return objectColor; }
            set { objectColor = value; }
        }

        public string Caption
        {
            get { return caption; }
            set { caption = value; }
        }

        public InspectionItem[] InspectionItems
        {
            get { return inspectionItems; }
            set { inspectionItems = value; }
        }
        #endregion Properties
    }
}
