using System;
using System.Collections.Generic;
using System.Text;
using System.Windows.Input;
using System.Windows.Media;
using System.Xml.Serialization;
using Common.Drawing.InspectionInformation;

namespace Common.Drawing
{
    public class PropertiesGraphicsMarkGuide : PropertiesGraphicsBase
    {
        private double left;
        private double top;
        private double right;
        private double bottom;

        private double cpX;
        private double cpY;

        #region Ctor.
        // For XmlSerializer
        public PropertiesGraphicsMarkGuide()
        {
            // XML로의 저장을 위해 기본 생성자가 필요하다.
            System.Diagnostics.Debug.WriteLine("PropertiesGraphicsGuideLine 기본 생성자 호출, 아무일도 하지 않는다.");
        }

        public PropertiesGraphicsMarkGuide(GraphicsMarkGuide stripguide)
        {
            if (stripguide == null)
            {
                throw new ArgumentNullException("stripguide");
            }
            this.left = stripguide.Left;
            this.top = stripguide.Top;
            this.right = stripguide.Right;
            this.bottom = stripguide.Bottom;

            this.cpX = stripguide.cpX;
            this.cpY = stripguide.cpY;
            this.lineWidth = stripguide.LineWidth;
            this.regionType = stripguide.RegionType;
            this.objectColor = stripguide.ObjectColor;
            this.actualScale = stripguide.ActualScale;
            this.Id = stripguide.ID;
            this.selected = stripguide.IsSelected;
            this.caption = stripguide.Caption;
        }
        #endregion

        public override GraphicsBase CreateGraphics()
        {
            lineWidth = 2; // Default thickness.

            actualScale = (actualScale > 0) ? actualScale : 1.0;
            GraphicsMarkGuide b = new GraphicsMarkGuide(left, right, cpY, lineWidth, objectColor, actualScale, 0);

            // GraphicsBase contains new ID generated by constructor.
            // This is OK if this instance is loaded from XML file.
            // But if this instance is part of commands history,
            // it contains ID which should be set in GraphicsBase.
            // This rule is applied to all SerializedGraphicsBase-derived
            // classes.
            if (this.Id != 0)       // from command history, not from file
            {
                b.ID = this.Id;
                b.IsSelected = this.selected;
            }

            return b;
        }

        #region Properties
        public int ID
        {
            get
            {
                return Id;
            }
            set
            {
                Id = value;
            }
        }

        public double Left
        {
            get { return left; }
            set { left = value; }
        }

        public double Top
        {
            get { return top; }
            set { top = value; }
        }

        public double Right
        {
            get { return right; }
            set { right = value; }
        }

        public double Bottom
        {
            get { return bottom; }
            set { bottom = value; }
        }


        public double CPX
        {
            get
            {
                return cpX;
            }
            set
            {
                cpX = value;
            }
        }

        public double CPY
        {
            get
            {
                return cpY;
            }
            set
            {
                cpY = value;
            }
        }

        public GraphicsRegionType RegionType
        {
            get
            {
                return regionType;
            }
            set
            {
                regionType = value;
            }

        }

        public Color ObjectColor
        {
            get
            {
                return objectColor;
            }
            set
            {
                objectColor = value;
            }
        }

        public string Caption
        {
            get
            {
                return caption;
            }
            set
            {
                caption = value;
            }
        }
        #endregion Properties
    }
}
