using System;
using System.Collections.Generic;
using System.Text;
using System.Windows.Input;
using System.Windows.Media;
using System.Xml.Serialization;
using Common.Drawing.InspectionInformation;

namespace Common.Drawing
{
    public class PropertiesGraphicsRailGuide : PropertiesGraphicsBase
    {
        private double left;
        private double top;
        private double right;
        private double bottom;
        private int basePoint;
        private System.Windows.Point firstPosition;

        #region Ctor.
        // For XmlSerializer
        public PropertiesGraphicsRailGuide()
        {
            // XML로의 저장을 위해 기본 생성자가 필요하다.
            System.Diagnostics.Debug.WriteLine("PropertiesGraphicsGuideLine 기본 생성자 호출, 아무일도 하지 않는다.");
        }

        public PropertiesGraphicsRailGuide(GraphicsRailGuide guideLine)
        {
            if (guideLine == null)
            {
                throw new ArgumentNullException("guideLine");
            }

            this.left = guideLine.Left;
            this.top = guideLine.Top;
            this.right = guideLine.Right;
            this.bottom = guideLine.Bottom;
            this.lineWidth = guideLine.LineWidth;
            this.regionType = guideLine.RegionType;
            this.objectColor = guideLine.ObjectColor;
            this.actualScale = guideLine.ActualScale;
            this.Id = guideLine.ID;
            this.selected = guideLine.IsSelected;
            this.caption = guideLine.Caption;
        }
        #endregion

        public override GraphicsBase CreateGraphics()
        {
            lineWidth = 2; // Default thickness.

            actualScale = (actualScale > 0) ? actualScale : 1.0;
            GraphicsGuideLine b = new GraphicsGuideLine(left, top, right, bottom, lineWidth, objectColor, actualScale, firstPosition);

            // GraphicsBase contains new ID generated by constructor.
            // This is OK if this instance is loaded from XML file.
            // But if this instance is part of commands history,
            // it contains ID which should be set in GraphicsBase.
            // This rule is applied to all SerializedGraphicsBase-derived
            // classes.
            if (this.Id != 0)       // from command history, not from file
            {
                b.ID = this.Id;
                b.IsSelected = this.selected;
            }

            return b;
        }

        #region Properties
        public int ID
        {
            get
            {
                return Id;
            }
            set
            {
                Id = value;
            }
        }

        public int BasePoint
        {
            get
            {
                return basePoint;
            }
            set
            {
                basePoint = value;
            }
        }

        public System.Windows.Point FirstPosition
        {
            get { return firstPosition; }
            set { firstPosition = value; }
        }

        public double Left
        {
            get
            {
                return left;
            }
            set
            {
                left = value;
            }
        }

        public double Top
        {
            get
            {
                return top;
            }
            set
            {
                top = value;
            }
        }

        public double Right
        {
            get
            {
                return right;
            }
            set
            {
                right = value;
            }
        }

        public double Bottom
        {
            get
            {
                return bottom;
            }
            set
            {
                bottom = value;
            }
        }

        public GraphicsRegionType RegionType
        {
            get
            {
                return regionType;
            }
            set
            {
                regionType = value;
            }

        }

        public Color ObjectColor
        {
            get
            {
                return objectColor;
            }
            set
            {
                objectColor = value;
            }
        }

        public string Caption
        {
            get
            {
                return caption;
            }
            set
            {
                caption = value;
            }
        }
        #endregion Properties
    }
}
