; Listing generated by Microsoft (R) Optimizing Compiler Version 19.00.24215.1 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\H180060\AppData\Local\Temp\.NETFramework,Version=v4.5.AssemblyAttributes.cpp"
