//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Resource {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessageList {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessageList() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Resource.ErrorMessageList", typeof(ErrorMessageList).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   통신을 초기화하지 못하였습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string C001 {
            get {
                return ResourceManager.GetString("C001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   로그를 원격지에 전송하는데 실패하였습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string C002 {
            get {
                return ResourceManager.GetString("C002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   아이디 또는 비밀번호 오류입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string C003 {
            get {
                return ResourceManager.GetString("C003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   데이터베이스 접속에 실패하였습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string C004 {
            get {
                return ResourceManager.GetString("C004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   유효한 Gerber 파일이 아닙니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string G001 {
            get {
                return ResourceManager.GetString("G001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   파일이 손상되었거나 너무 커서 뷰어가 이 사진을 열 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string I001 {
            get {
                return ResourceManager.GetString("I001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   유효한 티칭 파일이 아닙니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string I002 {
            get {
                return ResourceManager.GetString("I002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이미지를 읽어들이는데 실패하였습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string I003 {
            get {
                return ResourceManager.GetString("I003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   잘못된 로그 보관 일수 입력입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string L001 {
            get {
                return ResourceManager.GetString("L001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   디렉터리를 초기화하는데 실패하였습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M001 {
            get {
                return ResourceManager.GetString("M001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   유효한 Model 파일이 아닙니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M002 {
            get {
                return ResourceManager.GetString("M002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   유효한 Sheet 파일이 아닙니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M003 {
            get {
                return ResourceManager.GetString("M003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   유효한 Strip 파일이 아닙니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M004 {
            get {
                return ResourceManager.GetString("M004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   입력된 값이 허용 범위를 초과하였습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M005 {
            get {
                return ResourceManager.GetString("M005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   해당 스트립 정보를 찾을 수 없습니다.
        ///수정할 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M006 {
            get {
                return ResourceManager.GetString("M006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   해당 시트 정보를 찾을 수 없습니다.
        ///수정할 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M007 {
            get {
                return ResourceManager.GetString("M007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   해당 모델 정보를 찾을 수 없습니다.
        ///수정할 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M008 {
            get {
                return ResourceManager.GetString("M008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   현재 선택된 모델은 삭제할 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M009 {
            get {
                return ResourceManager.GetString("M009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Section 데이터를 DB에 저장하는데 실패하였습니다.
        ///연결 상태를 확인 후 다시 작업을 요청해 주시기 바랍니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MT001 {
            get {
                return ResourceManager.GetString("MT001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Section 데이터를 전송하는데 실패하였습니다. 
        ///Vision과의 연결 상태를 확인 후 다시 시도해 주시기 바랍니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MT002 {
            get {
                return ResourceManager.GetString("MT002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Section 이미지를 획득하는데 실패하였습니다.
        ///Vision과의 연결 상태를 확인 후 다시 시도해 주시기 바랍니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MT003 {
            get {
                return ResourceManager.GetString("MT003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   영상 획득에 실패하였습니다. 다시 시도해 주시기 바랍니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MT004 {
            get {
                return ResourceManager.GetString("MT004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vision과의 연결이 끊어졌습니다.
        ///문제가 지속되면 Vision을 다시 시작해 주시기 바랍니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MT005 {
            get {
                return ResourceManager.GetString("MT005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   읽어오려는 Teaching Data와 현재 선택된 모델이 다릅니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MT006 {
            get {
                return ResourceManager.GetString("MT006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   읽어오려는 Teaching Data가 현재 등록된 영상보다 큽니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MT007 {
            get {
                return ResourceManager.GetString("MT007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   동일한 시작 위치를 갖는 Section이 존재합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MT008 {
            get {
                return ResourceManager.GetString("MT008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   동일한 위치를 점유하는 Section이 존재합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MT009 {
            get {
                return ResourceManager.GetString("MT009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   올바른 값이 아닙니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string R001 {
            get {
                return ResourceManager.GetString("R001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   상면 또는 하면을 선택하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string R002 {
            get {
                return ResourceManager.GetString("R002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   색상을 선택하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string R003 {
            get {
                return ResourceManager.GetString("R003", resourceCulture);
            }
        }
    }
}
