//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Resource {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InformationMessageList {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InformationMessageList() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Resource.InformationMessageList", typeof(InformationMessageList).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   저장되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string C001 {
            get {
                return ResourceManager.GetString("C001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   삭제되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string C002 {
            get {
                return ResourceManager.GetString("C002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   삭제 실퍠하였습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string C003 {
            get {
                return ResourceManager.GetString("C003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   장비이름을 입력 바랍니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string E001 {
            get {
                return ResourceManager.GetString("E001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   장비이름 중복확인을 해주시기 바랍니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string E002 {
            get {
                return ResourceManager.GetString("E002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   선택된 장비를 삭제하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string E003 {
            get {
                return ResourceManager.GetString("E003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이미 등록된 이름입니다. 다시 입력해 주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string E004 {
            get {
                return ResourceManager.GetString("E004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   사용가능한 이름입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string E005 {
            get {
                return ResourceManager.GetString("E005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gerber 레이어는 8개까지만 등록됩니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string G001 {
            get {
                return ResourceManager.GetString("G001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gerber 레이어가 등록되어 있지 않습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string G002 {
            get {
                return ResourceManager.GetString("G002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   현재 동일한 작업이 수행중입니다.
        ///잠시후 시도해 주시기 바랍니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string G003 {
            get {
                return ResourceManager.GetString("G003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   검사이름을 입력 바랍니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string I001 {
            get {
                return ResourceManager.GetString("I001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   검사이름 중복확인을 해주시기 바랍니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string I002 {
            get {
                return ResourceManager.GetString("I002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   선택된 항목을 삭제하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string I003 {
            get {
                return ResourceManager.GetString("I003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이미 등록된 이름입니다. 다시 입력해 주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string I004 {
            get {
                return ResourceManager.GetString("I004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   사용가능한 이름입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string I005 {
            get {
                return ResourceManager.GetString("I005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&apos;1.0&apos; encoding=&apos;utf-8&apos;?&gt;&lt;XMLConfigSettings&gt;&lt;/XMLConfigSettings&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string IDS_DEFAULT_XML {
            get {
                return ResourceManager.GetString("IDS_DEFAULT_XML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   모델을 선택해 주시기 바랍니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string IS001 {
            get {
                return ResourceManager.GetString("IS001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이미지를 불러오신 후에 그리기 작업이 가능합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string IV001 {
            get {
                return ResourceManager.GetString("IV001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   로컬 파일 시스템에 로그를 저장합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string L001 {
            get {
                return ResourceManager.GetString("L001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   로컬 파일 시스템에 로그를 저장하지 않습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string L002 {
            get {
                return ResourceManager.GetString("L002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   새로운 스트립의 이름을 지정해주시기 바랍니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M001 {
            get {
                return ResourceManager.GetString("M001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   등록된 시트 정보가 없습니다.
        ///새로 생성해 주시기 바랍니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M002 {
            get {
                return ResourceManager.GetString("M002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   등록된 스트립 정보가 없습니다.
        ///새로 생성해 주시기 바랍니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M003 {
            get {
                return ResourceManager.GetString("M003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   시트 정보가 저장되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M004 {
            get {
                return ResourceManager.GetString("M004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   중복된 이름의 시트가 존재합니다.
        ///이름을 변경바랍니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M005 {
            get {
                return ResourceManager.GetString("M005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   스트립 정보가 저장되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M006 {
            get {
                return ResourceManager.GetString("M006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   중복된 이름의 스트립이 존재합니다.
        ///이름을 변경바랍니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M007 {
            get {
                return ResourceManager.GetString("M007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   선택된 항목을 삭제하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M008 {
            get {
                return ResourceManager.GetString("M008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   시트 정보가 수정되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M009 {
            get {
                return ResourceManager.GetString("M009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   스트립 정보가 수정되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M010 {
            get {
                return ResourceManager.GetString("M010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   새로운 시트의 이름을 지정해주시기 바랍니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M011 {
            get {
                return ResourceManager.GetString("M011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   새로운 모델의 이름을 지정해주시기 바랍니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M012 {
            get {
                return ResourceManager.GetString("M012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   입력한 내용을 취소하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M013 {
            get {
                return ResourceManager.GetString("M013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   변경된 사항을 저장하지 않고 마치시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M014 {
            get {
                return ResourceManager.GetString("M014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   변경된 사항이 있습니다.
        ///저장하고 다른 페이지를 탐색하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M015 {
            get {
                return ResourceManager.GetString("M015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   중복된 이름의 모델이 존재합니다.
        ///이름을 변경바랍니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M016 {
            get {
                return ResourceManager.GetString("M016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   모델 정보가 저장되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M017 {
            get {
                return ResourceManager.GetString("M017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   모델 정보가 수정되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M018 {
            get {
                return ResourceManager.GetString("M018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   모든 항목을 입력 바랍니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M019 {
            get {
                return ResourceManager.GetString("M019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   다음 문자를 사용할 수 없습니다.
        ///
        ///\ / : * ? &quot; &lt; &gt; |
        ///
        ///아래의 시스템 예약어를 사용할 수 없습니다.
        ///
        ///&quot;CON&quot;, &quot;PRN&quot;, &quot;AUX&quot;, &quot;NUL&quot;
        ///&quot;COM1&quot;, &quot;COM2&quot;, &quot;COM3&quot;, &quot;COM4&quot;, &quot;COM5&quot;
        ///&quot;COM6&quot;, &quot;COM7&quot;, &quot;COM8&quot;, &quot;COM9&quot;
        ///&quot;LPT1&quot;, &quot;LPT2&quot;, &quot;LPT3&quot;, &quot;LPT4&quot;, &quot;LPT5&quot;
        ///&quot;LPT6&quot;, &quot;LPT7&quot;, &quot;LPT8&quot;, &quot;LPT9&quot;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M020 {
            get {
                return ResourceManager.GetString("M020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;.&quot; 또는 &quot;..&quot;을 이름으로 가질 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M021 {
            get {
                return ResourceManager.GetString("M021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   모델이 속할 그룹을 생성하거나 선택해 주시기 바랍니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M022 {
            get {
                return ResourceManager.GetString("M022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   수정하려는 모델을 선택해 주시기 바랍니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M023 {
            get {
                return ResourceManager.GetString("M023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   삭제하려는 모델을 선택해 주시기 바랍니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M024 {
            get {
                return ResourceManager.GetString("M024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   수정하려는 분류를 선택해 주시기 바랍니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M025 {
            get {
                return ResourceManager.GetString("M025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   삭제하려는 분류를 선택해 주시기 바랍니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M026 {
            get {
                return ResourceManager.GetString("M026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   분류가 생성되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M027 {
            get {
                return ResourceManager.GetString("M027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   분류명이 변경되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M028 {
            get {
                return ResourceManager.GetString("M028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   선택된 분류가 삭제되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M029 {
            get {
                return ResourceManager.GetString("M029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   제품 폭은 0보다 커야 합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M030 {
            get {
                return ResourceManager.GetString("M030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   제품 길이는 0보다 커야 합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M031 {
            get {
                return ResourceManager.GetString("M031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   보정치는 0 이상의 값이 지정되어야 합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M032 {
            get {
                return ResourceManager.GetString("M032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   보정치는 제품의 크기를 초과할 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M033 {
            get {
                return ResourceManager.GetString("M033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Block은 최소 1개 이상이어야 합니다.
        ///(원맵 타입인 경우 1로 지정해 주십시오.)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M034 {
            get {
                return ResourceManager.GetString("M034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Block 수가 1인 경우 Pitch 값을 제품 크기와 동일하게 적용하여 저장합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M035 {
            get {
                return ResourceManager.GetString("M035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Block의 Pitch 값은 0보다 커야 합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M036 {
            get {
                return ResourceManager.GetString("M036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Block의 X축 Pitch 값은 제품의 길이를 초과할 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M037 {
            get {
                return ResourceManager.GetString("M037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Block의 Y축 Pitch 값은 제품의 길이를 초과할 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M038 {
            get {
                return ResourceManager.GetString("M038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unit은 최소 1개 이상이어야 합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M039 {
            get {
                return ResourceManager.GetString("M039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unit X축 개수는 Block X축 개수의 배수여야 합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M040 {
            get {
                return ResourceManager.GetString("M040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unit Y축 개수는 Block Y축 개수의 배수여야 합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M041 {
            get {
                return ResourceManager.GetString("M041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unit의 Pitch 값은 0보다 커야 합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M043 {
            get {
                return ResourceManager.GetString("M043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unit의 X축 Pitch 값은 제품의 길이를 초과할 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M044 {
            get {
                return ResourceManager.GetString("M044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unit의 Y축 Pitch 값은 제품의 폭을 초과할 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M045 {
            get {
                return ResourceManager.GetString("M045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   X축 Unit의 배열이 Block X축 Pitch 길이를 초과하였습니다. 확인바랍니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M046 {
            get {
                return ResourceManager.GetString("M046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Y축 Unit의 배열이 Block Y축 Pitch 길이를 초과하였습니다. 확인바랍니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M047 {
            get {
                return ResourceManager.GetString("M047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   X축 Unit의 배열이 제품의 길이를 초과하였습니다. 확인바랍니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M048 {
            get {
                return ResourceManager.GetString("M048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Y축 Unit의 배열이 제품의 폭을 초과하였습니다. 확인바랍니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M049 {
            get {
                return ResourceManager.GetString("M049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   X축 Block의 배열이 제품의 길이를 초과하였습니다. 확인바랍니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M050 {
            get {
                return ResourceManager.GetString("M050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Y축 Block의 배열이 제품의 폭을 초과하였습니다. 확인바랍니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M051 {
            get {
                return ResourceManager.GetString("M051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   저장에 실패하였습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M052 {
            get {
                return ResourceManager.GetString("M052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   분류 생성에 실패하였습니다. 다시 시도해 주시기 바랍니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M053 {
            get {
                return ResourceManager.GetString("M053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   분류 수정에 실패하였습니다. 다시 시도해 주시기 바랍니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M054 {
            get {
                return ResourceManager.GetString("M054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   분류 삭제에 실패하였습니다. 다시 시도해 주시기 바랍니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M055 {
            get {
                return ResourceManager.GetString("M055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   모델 생성에 실패하였습니다. 다시 시도해 주시기 바랍니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M056 {
            get {
                return ResourceManager.GetString("M056", resourceCulture);
            }
        }
        
        /// <summary>
        ///   모델 수정에 실패하였습니다. 다시 시도해 주시기 바랍니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M057 {
            get {
                return ResourceManager.GetString("M057", resourceCulture);
            }
        }
        
        /// <summary>
        ///   모델 삭제에 실패하였습니다. 다시 시도해 주시기 바랍니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M058 {
            get {
                return ResourceManager.GetString("M058", resourceCulture);
            }
        }
        
        /// <summary>
        ///   선택된 모델이 삭제되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M059 {
            get {
                return ResourceManager.GetString("M059", resourceCulture);
            }
        }
        
        /// <summary>
        ///   현재 선택된 모델은 삭제할 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M060 {
            get {
                return ResourceManager.GetString("M060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   현재 선택된 모델이 속한 그룹은 삭제할 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M061 {
            get {
                return ResourceManager.GetString("M061", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;\ / : * ? &apos; &quot; &lt; &gt; |&apos; 는 사용할 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M062 {
            get {
                return ResourceManager.GetString("M062", resourceCulture);
            }
        }
        
        /// <summary>
        ///   시스템 예약어는 사용할 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M063 {
            get {
                return ResourceManager.GetString("M063", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Block 열 개수는 Unit 열의 개수를 초과할 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M064 {
            get {
                return ResourceManager.GetString("M064", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Block 행 개수는 Unit 행의 개수를 초과할 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M065 {
            get {
                return ResourceManager.GetString("M065", resourceCulture);
            }
        }
        
        /// <summary>
        ///   모델을 선택해 주시기 바랍니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M066 {
            get {
                return ResourceManager.GetString("M066", resourceCulture);
            }
        }
        
        /// <summary>
        ///   로트를 선택해 주시기 바랍니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M067 {
            get {
                return ResourceManager.GetString("M067", resourceCulture);
            }
        }
        
        /// <summary>
        ///   제품 길이는 300보다 작아야 합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M068 {
            get {
                return ResourceManager.GetString("M068", resourceCulture);
            }
        }
        
        /// <summary>
        ///   제품 폭은 150보다 작아야 합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M069 {
            get {
                return ResourceManager.GetString("M069", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Total Units 는 (Unit X수 X Unit Y수) 와 같거나 이상 이어야  합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M070 {
            get {
                return ResourceManager.GetString("M070", resourceCulture);
            }
        }
        
        /// <summary>
        ///   등록된 모델이 없습니다.
        ///모델 정보를 생성해 주시기 바랍니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MS001 {
            get {
                return ResourceManager.GetString("MS001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ROI는 가로, 세로 30픽셀을 초과할 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MT001 {
            get {
                return ResourceManager.GetString("MT001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ROI 숨김 해제를 선택 후 작업을 수행해 주시기 바랍니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MT002 {
            get {
                return ResourceManager.GetString("MT002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   전체 영상 Section Type에 대해서만 파일로부터 영상을 읽어올 수 있습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MT003 {
            get {
                return ResourceManager.GetString("MT003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   영상이 저장되었습니다. 저장된 영상은 기준영상으로 사용됩니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MT004 {
            get {
                return ResourceManager.GetString("MT004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   티칭하려는 모델을 선택해 주시기 바랍니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MT005 {
            get {
                return ResourceManager.GetString("MT005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   영상을 저장하는데 실패하였습니다. 잠시 후 다시 시도해 주시기 바랍니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MT006 {
            get {
                return ResourceManager.GetString("MT006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   섹션 영역을 생성해 주시기 바랍니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MT007 {
            get {
                return ResourceManager.GetString("MT007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   반복 설정이 되지 않은 Unit 영역이 있습니다.
        ///반복 설정을 진행해 주시기 바랍니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MT008 {
            get {
                return ResourceManager.GetString("MT008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   영상을 등록 후 Teaching 파일을 열어주시기 바랍니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MT009 {
            get {
                return ResourceManager.GetString("MT009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   섹션영상이 저장되었습니다. 저장된 영상은 기준영상으로 사용됩니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MT010 {
            get {
                return ResourceManager.GetString("MT010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   기준 영상이 등록되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MT011 {
            get {
                return ResourceManager.GetString("MT011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   불량이름을 입력 바랍니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string N001 {
            get {
                return ResourceManager.GetString("N001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   불량이름 중복확인을 해주시기 바랍니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string N002 {
            get {
                return ResourceManager.GetString("N002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   선택된 불량정보를 삭제하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string N003 {
            get {
                return ResourceManager.GetString("N003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   중복된 이름입니다. 다시 입력해 주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string N004 {
            get {
                return ResourceManager.GetString("N004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   폐기이름을 입력 바랍니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string R001 {
            get {
                return ResourceManager.GetString("R001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   폐기이름 중복확인을 해주시기 바랍니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string R002 {
            get {
                return ResourceManager.GetString("R002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   선택된 폐기정보를 삭제하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string R003 {
            get {
                return ResourceManager.GetString("R003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이미 등록된 이름입니다. 다시 입력해 주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string R004 {
            get {
                return ResourceManager.GetString("R004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Strip 폐기율을 입력바랍니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string R005 {
            get {
                return ResourceManager.GetString("R005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unit 폐기율을 입력바랍니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string R006 {
            get {
                return ResourceManager.GetString("R006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   날짜를 입력해주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string R007 {
            get {
                return ResourceManager.GetString("R007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   올바른 날짜가 아닙니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string R008 {
            get {
                return ResourceManager.GetString("R008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이미지도 삭제됩니다. 계속하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string R009 {
            get {
                return ResourceManager.GetString("R009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   불량 이미지를 저장하지 않으시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string S001 {
            get {
                return ResourceManager.GetString("S001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   범위값이 올바르지 않습니다. 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string S002 {
            get {
                return ResourceManager.GetString("S002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID를 입력 바랍니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string U001 {
            get {
                return ResourceManager.GetString("U001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이름을 입력 바랍니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string U002 {
            get {
                return ResourceManager.GetString("U002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   비밀번호를 입력 바랍니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string U003 {
            get {
                return ResourceManager.GetString("U003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID 중복확인을 해주시기 바랍니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string U004 {
            get {
                return ResourceManager.GetString("U004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   새 비밀번호와 비밀번호 확인이 일치하지 않습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string U005 {
            get {
                return ResourceManager.GetString("U005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   비밀번호를 정확히 입력해 주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string U006 {
            get {
                return ResourceManager.GetString("U006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   선택된 항목을 삭제하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string U007 {
            get {
                return ResourceManager.GetString("U007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   비밀번호 확인을 입력해 주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string U008 {
            get {
                return ResourceManager.GetString("U008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   비밀번호와 비밀번호 확인이 일치하지 않습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string U009 {
            get {
                return ResourceManager.GetString("U009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이미 등록된 ID입니다. 다시 입력해 주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string U010 {
            get {
                return ResourceManager.GetString("U010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   사용가능한 ID입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string U011 {
            get {
                return ResourceManager.GetString("U011", resourceCulture);
            }
        }
    }
}
